apm-server:
  host: "0.0.0.0:8200"
  rum:
    enabled: true
  frontend:
    enabled: true
    allow_origins: ["*"]

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"